# Digital Pipeline Configuration
[Title]
Title=Digital Pipeline 3D2D

[Resolution]
width=1920
height=1080

[ModelOBJ]
Cube=models/Cube/cube.obj
Human=models/Human/Human.obj
Cup=models/Cup/Cup.obj

[ModelMTL]
Cube=models/Cube/cube.mtl
Human=models/Human/Human.mtl
Cup=models/Cup/Cup.mtl

[ModelPosition]
Cube= 0.0, 0.0, 0.0
Human= -5.0, 0.0, 0.0
Cup= 3.0, 1.0, 0.0

[ModelRotation]
Cube= 0.0, 0.0, 0.0
Human= 0.0, 180.0, -180.0
Cup= 0.0, 0.0, -180.0

[ModelScale]
Cube= 1.0, 1.0, 1.0
Human= 1.0, 1.0, 1.0
Cup= 1.0, 1.0, 1.0

[DirectionalLight]
direction= 0.0, -1.0, 0.0
color= 1.0, 1.0, 1.0
intensity=1.0

[SunMoonDirections]
sun= 0.0, -1.0, 0.0
moon= 0.0, 1.0, 0.0

[SeasonalTimings]
day=10.0
night=10.0
dry=20.0
snowy=20.0
wet=20.0